Updated index.html
BlackTimber-Labs/website pull request #1
Opened 2021-08-23 17:20 UTC by yashar1908

Changed a few sentences, made no change to the code as such...only changed the formation of the sentences that were displayed

2021-08-23 17:45 UTC, RITEKROUNAK commented
@Mahi-Badaya 
Please Review it Once.

2021-08-23 18:30 UTC, Mahi-Badaya requested changes
Please make the mentioned changes

2021-08-23 18:30 UTC, Mahi-Badaya commented on index.html
> +                      We provide to you, all the credits of <strong>development</strong>, So that the users can know who are  the<strong> Developers </strong>
-We provide you all the credits of
this will make more sense

2021-08-23 18:30 UTC, Mahi-Badaya commented on index.html
> +                      <p class="paragraph">We will push your apps on <strong>Google PlayStore</strong>  	and in the future, maybe <strong>AppStore</strong> as well :) So that you can only focus on de
Hmmm, it seems another cool reason.. isn’t it?

We can keep this line like this.

2021-08-23 18:30 UTC, Mahi-Badaya commented on index.html
> +                      <p class="paragraph">Having connections is really important, and what better way to connect than by working together on a project. Open source is meant <strong>FOR EVERYONE BY
No changes are required in the original content.

2021-08-23 18:30 UTC, Mahi-Badaya commented on index.html
> +                    <p class="paragraph">Yes, we know you must be thinking it doesn’t matter much but wait, there is a <strong>catch!</strong>! We provide 	Certificates with <strong>Certificate IDs</
only change matters to matter. else was okay previously.

2021-08-23 18:30 UTC, Mahi-Badaya commented on index.html
> +                        All your projects would be hosted for free at <strong>NO EXTRA COST!</strong> On BlackTimber-Labs' Physical 	Servers. Forget about those heavy charges by AWS , AZURE, GCLOUD e
Don't remove the line "Oops seems we started it from Bang! But yea, you heard it right." it's fine

2021-08-24 19:07 UTC, Mahi-Badaya approved these changes
It's okay now.

2021-08-24 19:08 UTC, merged

2021-08-24 19:24 UTC, yashar1908 commented
But I didn't change anything 😭😂

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Mahi Badaya ***@***.***>
Sent: Wednesday, August 25, 2021 12:37:15 AM
To: BlackTimber-Labs/website ***@***.***>
Cc: Yash Harvender Arora [CSE - 2020] ***@***.***>; Author ***@***.***>
Subject: Re: [BlackTimber-Labs/website] Updated index.html (#1)


@Mahi-Badaya approved this pull request.

It's okay now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/BlackTimber-Labs/website/pull/1#pullrequestreview-737589808>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARQP6KXY6JZZ4JCCGZNFDS3T6PUWHANCNFSM5CVA3BHA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>.